### ISSUE TITLE
adlr binary can't parse output from go list

### ISSUE THREAD

**Issue by ianhecker** [blocky/adlr#33]
When trying to use the adlr binary with output from `go list -m -json all > buildlist.json`, the binary returns the error `unexpected end of JSON input`

This is because `go list` outputs the imported dependencies of the module in a newline delimited list. It does not put commas after each module's json

```
{
        "Path": "rsc.io/quote/v3",
        "Version": "v3.1.0",
        "Time": "2019-03-12T14:59:12Z",
        "Indirect": true,
        "GoMod": "/home/ian/go/pkg/mod/cache/download/rsc.io/quote/v3/@v/v3.1.0.mod"
}
{
        "Path": "rsc.io/sampler",
        "Version": "v1.3.0",
        "Time": "2018-02-13T19:05:03Z",
        "Indirect": true,
        "GoMod": "/home/ian/go/pkg/mod/cache/download/rsc.io/sampler/@v/v1.3.0.mod"
}
... etc
```

Currently, using the `gotool` package included in ADLR for marshaling from the buildlist works, and handles this newline delimited list correctly

**Comment by tahardi** [comment]
The use of `go list` was removed in ADLR V2 as we simply use go.mod now.
